Brunostar
transkript/reportcard-backend pull request #14
Opened 2022-05-16 19:53 UTC by Brunostar

2022-05-17 15:25 UTC, elroykanye commented
Please give a pull request title that describes your changes. It will be nice to have look back into the past some time to code like this.

2022-05-17 16:01 UTC, elroykanye requested changes
Checkout the comments below

2022-05-18 16:47 UTC, elroykanye requested changes
Please give a pull request title that describes your changes. It will be nice to have look back into the past some time to code like this.

2022-05-18 17:40 UTC, merged

2022-05-19 08:48 UTC, Brunostar commented on rc-application/src/main/java/com/transkript/reportcard/business/service/impl/SectionServiceImpl.java
> +            section.setSchool(school);
Null checking is done in the getSchoolById method